### ISSUE TITLE
Error using CPU for voice cloning

### ISSUE THREAD

**Issue by xAIxxxxNAGI** [rsxdalv/tts-generation-webui#86]
Hi, I faced this error when I tried to do a bark voice clone.

```
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
```

I'm using a mac m2, and my device does not have proper GPU, so I unchecked "use GPT", but it still gets the issue.

<img width="1315" alt="Screenshot 2023-07-21 at 15 41 58" src="https://github.com/rsxdalv/tts-generation-webui/assets/139841059/916e460c-b1e2-4375-9b38-619c43c8c783">

Can you please help to check this??

**Comment by rsxdalv** [comment]
Thank you for your analysis, I found the bug and reproduced it. 
Use GPU was only applied to 1 of the 2 models.
Hopefully I can have a fix out soon.

**Comment by rsxdalv** [comment]
I tested the fix and it should work now with either CPU or GPU. If you accidentally cause an error, use the "clear models" button. Before unchecking/checking the checkbox.

https://github.com/rsxdalv/tts-generation-webui/pull/87

**Comment by xAIxxxxNAGI** [comment]
Hi, thank you for the quick fix, I updated it, and it works well!

Let me close the issue.

**Comment by rsxdalv** [comment]
I got the fixes merged into the original package, so hopefully * all * of the hubert voice cloning projects should be more CPU compatible now.
